name: ESLint
on: [pull_request]
jobs:
    typescript:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 14.19.0
            - name: Install dependencies
              run: yarn --frozen-lockfile
            - name: TypeScript
              run: yarn tsc --noEmit --skipLibCheck
